# Базовий офіційний образ MySQL
FROM mysql:latest

# Змінні оточення для ініціалізації бази даних та користувача
ENV MYSQL_ROOT_PASSWORD=root_secure_pass
ENV MYSQL_DATABASE=app_db
ENV MYSQL_USER=app_user
ENV MYSQL_PASSWORD=1234
